// Carrying a BUYER referral code from the link to the sign-in (2026-08-31).
//
// Separate from lib/referralCode.ts, which is the VENDOR signup's own capture
// and has been there far longer. They look alike and are not interchangeable:
// the two code spaces are generated by different systems (vendor codes by
// utils/referralCode.js, buyer codes by the Firebase auth controller), and
// sending one where the other is expected would either match nobody or, worse,
// match somebody unrelated. Distinct storage keys keep a vendor's captured
// code from ever being posted as a buyer's.
//
// Why store it at all: a buyer arrives on /chat?ref=ABCD2345, uses Velte for a
// while, and signs in later — often several searches later, when their guest
// credits run out, which is exactly when the referral is most likely to
// convert. By then the query string is long gone.
//
// Cleared only on SUCCESS, so a failed or abandoned sign-in doesn't cost the
// referrer their bonus.

const KEY = "velte:buyer-referral-code";

/** Codes are generated server-side from a 32-symbol alphabet with no
 *  look-alike characters (no 0/O/1/I — see the backend's newReferralCode).
 *  Validated here rather than trusted, so a hand-edited storage value can't
 *  be posted at the auth endpoint as an arbitrary string. */
const CODE = /^[2-9A-HJ-NP-Z]{4,16}$/;

/** Reads `?ref=` off the current URL and remembers it. Safe to call on every
 *  mount: an absent or malformed code leaves whatever was already stored, so
 *  navigating within the app cannot wipe a code captured on arrival. */
export function captureBuyerReferralCode(): void {
  if (typeof window === "undefined") return;
  try {
    const raw = new URLSearchParams(window.location.search).get("ref");
    if (!raw) return;
    const code = raw.trim().toUpperCase();
    if (!CODE.test(code)) return;
    window.localStorage.setItem(KEY, code);
  } catch {
    // Blocked storage means the referral simply isn't attributed. It must
    // never break the page it was captured on.
  }
}

/** The code to send with a sign-in, or undefined. */
export function storedBuyerReferralCode(): string | undefined {
  if (typeof window === "undefined") return undefined;
  try {
    const code = window.localStorage.getItem(KEY);
    return code && CODE.test(code) ? code : undefined;
  } catch {
    return undefined;
  }
}

/** Called once an account exists. Stops a stale code being re-sent on a later
 *  sign-in — the backend's idempotency would refuse the second bonus anyway,
 *  but leaving it lying around invites the question. */
export function clearBuyerReferralCode(): void {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.removeItem(KEY);
  } catch {
    // Nothing to do — an uncleared code is refused server-side regardless.
  }
}
