const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

export interface Category {
  id: string;
  name: string;
  emoji: string;
  bgColor: string;
  description?: string;
}

export type ProductTab = "all" | "featured" | "on-sale" | "out-of-stock";

export interface CategoryProduct {
  id: string;
  name: string;
  categoryId: string;
  createdDate: string;
  orders: number;
  featured: boolean;
  onSale: boolean;
  inStock: boolean;
  colorClass: string;
}

export const CATEGORIES_DATA: Category[] = [
  {
    id: "electronics",
    name: "Electronics",
    emoji: "💻",
    bgColor: "bg-blue-100",
    description: "Gadgets, devices and tech accessories",
  },
  {
    id: "fashion",
    name: "Fashion",
    emoji: "👗",
    bgColor: "bg-pink-100",
    description: "Clothing, footwear and apparel",
  },
  {
    id: "accessories",
    name: "Accessories",
    emoji: "👜",
    bgColor: "bg-amber-100",
    description: "Bags, wallets, belts and more",
  },
  {
    id: "home-kitchen",
    name: "Home & Kitchen",
    emoji: "🏠",
    bgColor: "bg-teal-100",
    description: "Appliances, cookware and home decor",
  },
  {
    id: "sports",
    name: "Sports & Outdoors",
    emoji: "⚽",
    bgColor: "bg-green-100",
    description: "Equipment, gear and outdoor essentials",
  },
  {
    id: "toys",
    name: "Toys & Games",
    emoji: "🎮",
    bgColor: "bg-purple-100",
    description: "Toys, board games and entertainment",
  },
  {
    id: "health",
    name: "Health & Fitness",
    emoji: "💪",
    bgColor: "bg-red-100",
    description: "Supplements, fitness gear and wellness",
  },
  {
    id: "books",
    name: "Books",
    emoji: "📚",
    bgColor: "bg-yellow-100",
    description: "Fiction, non-fiction and educational",
  },
];

export const PRODUCTS_DATA: CategoryProduct[] = [
  // Electronics
  {
    id: "p1",
    name: "Wireless Bluetooth Headphones",
    categoryId: "electronics",
    createdDate: "01-01-2025",
    orders: 25,
    featured: true,
    onSale: false,
    inStock: true,
    colorClass: "bg-blue-200",
  },
  {
    id: "p2",
    name: "Full HD Webcam",
    categoryId: "electronics",
    createdDate: "01-01-2025",
    orders: 20,
    featured: false,
    onSale: true,
    inStock: true,
    colorClass: "bg-blue-300",
  },
  {
    id: "p3",
    name: "Smart LED Color Bulb",
    categoryId: "electronics",
    createdDate: "01-01-2025",
    orders: 16,
    featured: false,
    onSale: false,
    inStock: true,
    colorClass: "bg-blue-200",
  },
  {
    id: "p4",
    name: "Mechanical Keyboard",
    categoryId: "electronics",
    createdDate: "02-01-2025",
    orders: 30,
    featured: true,
    onSale: true,
    inStock: true,
    colorClass: "bg-blue-300",
  },
  {
    id: "p5",
    name: "USB-C Hub",
    categoryId: "electronics",
    createdDate: "02-01-2025",
    orders: 45,
    featured: false,
    onSale: false,
    inStock: true,
    colorClass: "bg-blue-200",
  },
  {
    id: "p6",
    name: "Smart Watch Series 5",
    categoryId: "electronics",
    createdDate: "03-01-2025",
    orders: 60,
    featured: true,
    onSale: false,
    inStock: false,
    colorClass: "bg-blue-300",
  },
  {
    id: "p7",
    name: "Portable Charger 20000mAh",
    categoryId: "electronics",
    createdDate: "03-01-2025",
    orders: 35,
    featured: false,
    onSale: true,
    inStock: true,
    colorClass: "bg-blue-200",
  },
  {
    id: "p8",
    name: "Noise Cancelling Earbuds",
    categoryId: "electronics",
    createdDate: "04-01-2025",
    orders: 28,
    featured: true,
    onSale: false,
    inStock: true,
    colorClass: "bg-blue-300",
  },
  // Fashion
  {
    id: "p9",
    name: "Men's Classic T-Shirt",
    categoryId: "fashion",
    createdDate: "01-01-2025",
    orders: 20,
    featured: false,
    onSale: true,
    inStock: true,
    colorClass: "bg-pink-200",
  },
  {
    id: "p10",
    name: "Casual Baseball Cap",
    categoryId: "fashion",
    createdDate: "01-01-2025",
    orders: 55,
    featured: true,
    onSale: false,
    inStock: true,
    colorClass: "bg-pink-300",
  },
  {
    id: "p11",
    name: "Men's Polo Shirt Blue",
    categoryId: "fashion",
    createdDate: "05-01-2025",
    orders: 10,
    featured: false,
    onSale: false,
    inStock: false,
    colorClass: "bg-pink-200",
  },
  {
    id: "p12",
    name: "Women's Summer Dress",
    categoryId: "fashion",
    createdDate: "05-01-2025",
    orders: 40,
    featured: true,
    onSale: true,
    inStock: true,
    colorClass: "bg-pink-300",
  },
  {
    id: "p13",
    name: "Denim Jacket Classic",
    categoryId: "fashion",
    createdDate: "06-01-2025",
    orders: 22,
    featured: false,
    onSale: false,
    inStock: true,
    colorClass: "bg-pink-200",
  },
  {
    id: "p14",
    name: "Hoodie Sweatshirt Grey",
    categoryId: "fashion",
    createdDate: "06-01-2025",
    orders: 18,
    featured: false,
    onSale: true,
    inStock: true,
    colorClass: "bg-pink-300",
  },
  // Accessories
  {
    id: "p15",
    name: "Men's Leather Wallet",
    categoryId: "accessories",
    createdDate: "01-01-2025",
    orders: 35,
    featured: false,
    onSale: false,
    inStock: true,
    colorClass: "bg-amber-200",
  },
  {
    id: "p16",
    name: "Men's Leather Wallet Black",
    categoryId: "accessories",
    createdDate: "01-01-2025",
    orders: 35,
    featured: true,
    onSale: false,
    inStock: true,
    colorClass: "bg-amber-300",
  },
  {
    id: "p17",
    name: "Canvas Tote Bag",
    categoryId: "accessories",
    createdDate: "07-01-2025",
    orders: 15,
    featured: false,
    onSale: true,
    inStock: true,
    colorClass: "bg-amber-200",
  },
  {
    id: "p18",
    name: "Polarized Sunglasses",
    categoryId: "accessories",
    createdDate: "07-01-2025",
    orders: 42,
    featured: true,
    onSale: false,
    inStock: false,
    colorClass: "bg-amber-300",
  },
  {
    id: "p19",
    name: "Genuine Leather Belt",
    categoryId: "accessories",
    createdDate: "08-01-2025",
    orders: 25,
    featured: false,
    onSale: true,
    inStock: true,
    colorClass: "bg-amber-200",
  },
  // Home & Kitchen
  {
    id: "p20",
    name: "Memory Foam Pillow",
    categoryId: "home-kitchen",
    createdDate: "01-01-2025",
    orders: 40,
    featured: true,
    onSale: false,
    inStock: true,
    colorClass: "bg-teal-200",
  },
  {
    id: "p21",
    name: "Coffee Maker 12-Cup",
    categoryId: "home-kitchen",
    createdDate: "01-01-2025",
    orders: 45,
    featured: false,
    onSale: true,
    inStock: true,
    colorClass: "bg-teal-300",
  },
  {
    id: "p22",
    name: "Non-Stick Frying Pan",
    categoryId: "home-kitchen",
    createdDate: "08-01-2025",
    orders: 32,
    featured: false,
    onSale: false,
    inStock: true,
    colorClass: "bg-teal-200",
  },
  {
    id: "p23",
    name: "Stainless Steel Kettle",
    categoryId: "home-kitchen",
    createdDate: "09-01-2025",
    orders: 28,
    featured: true,
    onSale: true,
    inStock: true,
    colorClass: "bg-teal-300",
  },
  {
    id: "p24",
    name: "Digital Air Fryer 5L",
    categoryId: "home-kitchen",
    createdDate: "09-01-2025",
    orders: 67,
    featured: true,
    onSale: false,
    inStock: false,
    colorClass: "bg-teal-200",
  },
  {
    id: "p25",
    name: "Cutting Board Set 3pc",
    categoryId: "home-kitchen",
    createdDate: "10-01-2025",
    orders: 19,
    featured: false,
    onSale: true,
    inStock: true,
    colorClass: "bg-teal-300",
  },
  {
    id: "p26",
    name: "Food Storage Containers",
    categoryId: "home-kitchen",
    createdDate: "10-01-2025",
    orders: 38,
    featured: false,
    onSale: false,
    inStock: true,
    colorClass: "bg-teal-200",
  },
  // Sports & Outdoors
  {
    id: "p27",
    name: "Premium Yoga Mat 6mm",
    categoryId: "sports",
    createdDate: "11-01-2025",
    orders: 50,
    featured: true,
    onSale: false,
    inStock: true,
    colorClass: "bg-green-200",
  },
  {
    id: "p28",
    name: "Resistance Bands Set 5pc",
    categoryId: "sports",
    createdDate: "11-01-2025",
    orders: 33,
    featured: false,
    onSale: true,
    inStock: true,
    colorClass: "bg-green-300",
  },
  {
    id: "p29",
    name: "Insulated Water Bottle",
    categoryId: "sports",
    createdDate: "12-01-2025",
    orders: 44,
    featured: false,
    onSale: false,
    inStock: true,
    colorClass: "bg-green-200",
  },
  {
    id: "p30",
    name: "Trail Running Shoes",
    categoryId: "sports",
    createdDate: "12-01-2025",
    orders: 27,
    featured: true,
    onSale: true,
    inStock: false,
    colorClass: "bg-green-300",
  },
  {
    id: "p31",
    name: "2-Person Camping Tent",
    categoryId: "sports",
    createdDate: "13-01-2025",
    orders: 12,
    featured: false,
    onSale: false,
    inStock: true,
    colorClass: "bg-green-200",
  },
  // Toys & Games
  {
    id: "p32",
    name: "Creative Building Blocks",
    categoryId: "toys",
    createdDate: "13-01-2025",
    orders: 29,
    featured: true,
    onSale: false,
    inStock: true,
    colorClass: "bg-purple-200",
  },
  {
    id: "p33",
    name: "Remote Control Racing Car",
    categoryId: "toys",
    createdDate: "14-01-2025",
    orders: 36,
    featured: false,
    onSale: true,
    inStock: true,
    colorClass: "bg-purple-300",
  },
  {
    id: "p34",
    name: "Wooden Chess Board Set",
    categoryId: "toys",
    createdDate: "14-01-2025",
    orders: 18,
    featured: false,
    onSale: false,
    inStock: false,
    colorClass: "bg-purple-200",
  },
  {
    id: "p35",
    name: "1000-Piece Puzzle",
    categoryId: "toys",
    createdDate: "15-01-2025",
    orders: 24,
    featured: true,
    onSale: true,
    inStock: true,
    colorClass: "bg-purple-300",
  },
  // Health & Fitness
  {
    id: "p36",
    name: "Whey Protein Powder Vanilla",
    categoryId: "health",
    createdDate: "15-01-2025",
    orders: 61,
    featured: true,
    onSale: false,
    inStock: true,
    colorClass: "bg-red-200",
  },
  {
    id: "p37",
    name: "Multivitamin Gummies 60ct",
    categoryId: "health",
    createdDate: "16-01-2025",
    orders: 48,
    featured: false,
    onSale: true,
    inStock: true,
    colorClass: "bg-red-300",
  },
  {
    id: "p38",
    name: "High-Density Foam Roller",
    categoryId: "health",
    createdDate: "16-01-2025",
    orders: 23,
    featured: false,
    onSale: false,
    inStock: true,
    colorClass: "bg-red-200",
  },
  {
    id: "p39",
    name: "Adjustable Dumbbell Set",
    categoryId: "health",
    createdDate: "17-01-2025",
    orders: 15,
    featured: true,
    onSale: true,
    inStock: false,
    colorClass: "bg-red-300",
  },
  {
    id: "p40",
    name: "Speed Jump Rope Pro",
    categoryId: "health",
    createdDate: "17-01-2025",
    orders: 31,
    featured: false,
    onSale: false,
    inStock: true,
    colorClass: "bg-red-200",
  },
  {
    id: "p41",
    name: "Posture Corrector Brace",
    categoryId: "health",
    createdDate: "18-01-2025",
    orders: 20,
    featured: false,
    onSale: true,
    inStock: true,
    colorClass: "bg-red-300",
  },
  // Books
  {
    id: "p42",
    name: "Atomic Habits",
    categoryId: "books",
    createdDate: "18-01-2025",
    orders: 55,
    featured: true,
    onSale: false,
    inStock: true,
    colorClass: "bg-yellow-200",
  },
  {
    id: "p43",
    name: "Zero to One",
    categoryId: "books",
    createdDate: "19-01-2025",
    orders: 34,
    featured: true,
    onSale: true,
    inStock: true,
    colorClass: "bg-yellow-300",
  },
  {
    id: "p44",
    name: "Rich Dad Poor Dad",
    categoryId: "books",
    createdDate: "19-01-2025",
    orders: 67,
    featured: false,
    onSale: false,
    inStock: true,
    colorClass: "bg-yellow-200",
  },
  {
    id: "p45",
    name: "The Art of War",
    categoryId: "books",
    createdDate: "20-01-2025",
    orders: 28,
    featured: false,
    onSale: false,
    inStock: false,
    colorClass: "bg-yellow-300",
  },
];

export const categoriesApi = {
  getCategories: async (): Promise<Category[]> => {
    await delay(300);
    return [...CATEGORIES_DATA];
  },
  getProducts: async (): Promise<CategoryProduct[]> => {
    await delay(400);
    return [...PRODUCTS_DATA];
  },
  createCategory: async (data: Omit<Category, "id">): Promise<Category> => {
    await delay(300);
    return { ...data, id: `cat-${Date.now()}` };
  },
  updateCategory: async (
    id: string,
    data: Partial<Category>,
  ): Promise<Category> => {
    await delay(300);
    const existing = CATEGORIES_DATA.find((c) => c.id === id);
    return { ...existing!, ...data };
  },
  deleteCategory: async (id: string): Promise<void> => {
    await delay(300);
  },
};
